### PR TITLE
Implement persistent session feature

### PR DESCRIPTION
**Pull request by kevinzhuang10**
https://trello.com/c/akrM1vAT

### CODE REVIEW

**Comment by clarencebowen** [comment]
Where is the ticket for this? It says it cannot be found

**Comment by kevinzhuang10** [comment]
https://trello.com/c/akrM1vAT

Try it again. I'm not sure why the last link didn't work

**Comment by clarencebowen** [comment]
Sorry, I see it. I would suggest adding the PR to the ticket though, and fixing the typo in the PR for 'session'

**Comment by kevinzhuang10** [comment]
Just did.

**Comment by clarencebowen** [comment]
Looks good. Please merge

**Pull request merged**
